name: chess_woodpecker_backend
description: Backend service for Chess Woodpecker application
version: 1.0.0
repository: https://github.com/drmDev/ChessWoodpecker

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  shelf: ^1.4.1
  shelf_router: ^1.1.3
  postgres: ^3.5.6
  dotenv: ^4.1.0
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.7
  # NOTE: this json_serializable version is required for the build_runner to work
  json_serializable: ^6.7.1
  # NOTE: this analyzer version is required for the build_runner to work
  analyzer: ^6.2.0
  http: ^1.1.0
  lints: ^5.0.0
  test: ^1.24.3
